import type {Metadata} from 'next';
import './globals.css';
import Header from '@/app/_component/header/Header';
import {homeLayoutContainer} from '@/app/home.style';
import {ApolloWrapper} from "@/app/_provider/ApolloWrapper";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={homeLayoutContainer()}>
        <ApolloWrapper>
            <Header/>
            {children}
        </ApolloWrapper>
        </body>
        </html>
    );
}
